version: 2

# Build all formats
formats: all

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: redoc/requirements.txt
    - method: pip
      path: .
