site_name: Commonground Gateway
repo_url: https://github.com/ConductionNL/commonground-gateway/
docs_dir: redoc
theme: readthedocs
nav:
    - "index.md"
    - "getting_started.md"
    - "how_does_it_work.md"
    - "features.md"
    - "design_decisions.md"
    - "contributing.md"
    - "installation.md"
    - "security.md"
