parameters:
    components:
#        uc:
#            auth: apikey
#            location: http://user-component
#            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        brp:
            auth: apikey
            location: https://digispoof.common-ground.dev/api/v1/brp
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845

        # Oude Taalhuizen dependencies:
        uc:
            auth: apikey
            location: https://taalhuizen-bisc.commonground.nu/api/v2/uc
            apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
        cc:
            auth: apikey
            location: https://taalhuizen-bisc.commonground.nu/api/v1/cc
            apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
#        edu:
#            auth: apikey
#            location: https://taalhuizen-bisc.commonground.nu/api/v1/edu
#            apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
#        mrc:
#            auth: apikey
#            location: https://taalhuizen-bisc.commonground.nu/api/v1/mrc
#            apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
#        bs:
#            auth: apikey
#            location: https://taalhuizen-bisc.commonground.nu/api/v1/bs
#            apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
#        nrc:
#            auth: apikey
#            location: https://taalhuizen-bisc.commonground.nu/api/v1/nrc
#            apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
