parameters:
    components:
        brp:
            auth: username-password
            location: http://vrij-brp.demodam.nl/haal-centraal-brp-bevragen/api/v1.3
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
            accept: application/hal+json
            username: begraven
            password: demodam
        ds:
            auth: apikey
            location: https://digispoof.demodam.nl/
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        uc:
            auth: apikey
            location: https://conduction.demodam.nl/api/v1/uc
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        cc:
            auth: apikey
            location: https://conduction.demodam.nl/api/v1/cc
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        bs:
            auth: apikey
            location: https://conduction.demodam.nl/api/v1/bs
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        nrc:
            auth: apikey
            location: https://conduction.demodam.nl/api/v1/nrc
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        dcs:
            auth: apikey
            location: https://conduction.demodam.nl/api/v1/document-creation-service
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
        vrc:
            auth: apikey
            apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
            location: https://conduction.demodam.nl/api/v1/vrc
