doctrine:
    dbal:
        connections:
            default:
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '13'
                url: '%env(resolve:DATABASE_URL)%'
            data_warehouse:
                url: '%env(resolve:DATAWAREHOUSE_URL)%'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            datetime:  Conduction\CommonGroundBundle\Types\UTCDateTimeType  #We override the default doctrine datetime with a UTC based version
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            data_warehouse:
                connection: data_warehouse
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                class_metadata_factory_name: Doctrine\ORM\Tools\DisconnectedClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
#                mappings:
#                    Main:
#                        is_bundle: false
#                        type: gateway
#                        dir: '%kernel.project_dir%/src/CustomEntity'
#                        prefix: 'App\CustomEntity'
