security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        authenticationProvider:
            id: App\Security\User\AuthenticationProvider
    firewalls:
        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: app_user_login
                check_path: app_user_login
            logout:
                path: app_user_logout
                target: app_user_redirect
            stateless: false
            provider: authenticationProvider
            guard:
                authenticators:
                    - App\Security\DigispoofAuthenticator
                    - App\Security\OauthAuthenticator
                entry_point: App\Security\OauthAuthenticator
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
