App\Entity\Organization:
    defaultOrganization:
#        id: <\Ramsey\Uuid\Uuid::fromString('a1c8e0b6-2f78-480d-a9fb-9792142f4761')>
        id: a1c8e0b6-2f78-480d-a9fb-9792142f4761
        name: default organization
        description: the default organization
        emails:
            - '@defaultOrganization_email'
        telephones:
            - '@defaultOrganization_telephone'
        addresses:
            - '@defaultOrganization_address'

App\Entity\Person:
    defaultPerson:
#        id: <\Ramsey\Uuid\Uuid::fromString('d2a24edf-6ced-40a2-8e7c-56803f4ce3f5')>
        id: d2a24edf-6ced-40a2-8e7c-56803f4ce3f5
        givenName: John
        additionalName: Allen
        familyName: Doe
        emails:
            - '@defaultPerson_email'
        telephones:
            - '@defaultPerson_telephone'
        addresses:
            - '@defaultPerson_address'
        
App\Entity\Email:
    defaultOrganization_email:
        name: email for default organization
        email: default-organization@test.com
        
    defaultPerson_email:
        name: email for default person
        email: default-person@test.com

App\Entity\Address:
    defaultOrganization_address:
        name: address for default organization
        street: somestreet
        houseNumber: 42
        postalCode: 6996
        locality: Utrecht
        
    defaultPerson_address:
        name: address for default person
        street: someotherstreet
        houseNumber: 666
        postalCode: 1234
        locality: Amsterdam

App\Entity\Telephone:
    defaultOrganization_telephone:
        name: telephone for default organization
        telephone: 0612345678
    
    defaultPerson_telephone:
        name: telephone for default person
        telephone: 0687654321
